export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
};

export const registerConstants = {
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
};

export const uploadImage = {
  UPLOAD_IMAGE_REQUEST: 'UPLOAD_IMAGE_REQUEST',
  UPLOAD_IMAGE_FAILURE: 'UPLOAD_IMAGE_FAILURE',
  UPLOAD_IMAGE_SUCCESS: 'UPLOAD_IMAGE_SUCCESS'
};

export const formationConstants = {
  GET_FORMATION_REQUEST: 'GET_FORMATION_REQUEST',
  GET_FORMATION_FAILURE: 'GET_FORMATION_FAILURE',
  GET_FORMATION_SUCCESS: 'GET_FORMATION_SUCCESS',
  GET_FORMATION_BY_Name_REQUEST: 'GET_FORMATION_BY_Name_REQUEST',
  GET_FORMATION_BY_Name_SUCCESS : 'GET_FORMATION_BY_Name_SUCCESS',
  GET_FORMATION_BY_Name_FAILURE: 'GET_FORMATION_BY_Name_FAILURE'
};

export const DeleteformationConstants = {
  DELETE_FORMATION_REQUEST: 'DELETE_FORMATION_REQUEST',
  DELETE_FORMATION_FAILURE: 'DELETE_FORMATION_FAILURE',
  DELETE_FORMATION_SUCCESS: 'DELETE_FORMATION_SUCCESS',
};

export const ADDformationConstants = {
  ADD_FORMATION_REQUEST: 'ADD_FORMATION_REQUEST',
  ADD_FORMATION_FAILURE: 'ADD_FORMATION_FAILURE',
  ADD_FORMATION_SUCCESS: 'ADD_FORMATION_SUCCESS',
};
export const formationgetByIdCentreConstants = {
  GETByIdCentre_FORMATION_REQUEST: 'GETByIdCentre_FORMATION_REQUEST',
  GETByIdCentre_FORMATION_FAILURE: 'GETByIdCentre_FORMATION_FAILURE',
  GETByIdCentre_FORMATION_SUCCESS: 'GETByIdCentre_FORMATION_SUCCESS',    

};
export const centre_formationConstants = {
  GET_CENTRE_FORMATION_REQUEST: 'GET_CENTRE_FORMATION_REQUEST',
  GET_CENTRE_FORMATION_FAILURE: 'GET_CENTRE_FORMATION_FAILURE',
  GET_CENTRE_FORMATION_SUCCESS: 'GET_CENTRE_FORMATION_SUCCESS',
  UPDATE_CENTER_REQUEST: 'UPDATE_CENTER_REQUEST',
  UPDATE_CENTER_FAILURE: 'UPDATE_CENTER_FAILURE',
  UPDATE_CENTER_SUCCESS: 'UPDATE_CENTER_SUCCESS',
  GET_BY_NOM_CENTER_REQUEST : 'GET_BY_NOM_CENTER_REQUEST',
  GET_BY_NOM_CENTER_FAILURE: 'GET_BY_NOM_CENTER_FAILURE',
  GET_BY_NOM_CENTER_SUCCESS : 'GET_BY_NOM_CENTER_SUCCESS'
};

export const GETBYIDUSERCENTREConstants = {
  GETBYIDUSER_CENTRE_REQUEST: 'GETBYIDUSER_CENTRE_REQUEST',
  GETBYIDUSER_CENTRE_FAILURE: 'GETBYIDUSER_CENTRE_FAILURE',
  GETBYIDUSER_CENTRE_SUCCESS: 'GETBYIDUSER_CENTRE_SUCCESS',
};

export const formateurConstants = {
  GET_FORMATEUR_REQUEST: 'GET_FORMATEUR_REQUEST',
  GET_FORMATEUR_FAILURE: 'GET_FORMATEUR_FAILURE',
  GET_FORMATEUR_SUCCESS: 'GET_FORMATEUR_SUCCESS',
  GET_BY_PRENOM_FORMATEUR_REQUEST : 'GET_BY_PRENOM_FORMATEUR_REQUEST',
  GET_BY_PRENOM_FORMATEUR_FAILURE: 'GET_BY_PRENOM_FORMATEUR_FAILURE',
  GET_BY_PRENOM_FORMATEUR_SUCCESS : 'GET_BY_PRENOM_FORMATEUR_SUCCESS'
};


export const getUserConstants = {
  GET_USER_REQUEST: 'GET_USER_REQUEST',
  GET_USER_FAILURE: 'GET_USER_FAILURE',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_VILLE_SUCCESS: 'GET_VILLE_SUCCESS',
  GET_VILLE_FAILURE: 'GET_VILLE_FAILURE',
  GET_VILLE_REQUEST: 'GET_VILLE_REQUEST' 
};


export const updatecandidatConstants = {
  UPDATE_CANDIDAT_REQUEST: 'UPDATE_CANDIDAT_REQUEST',
  UPDATE_CANDIDAT_FAILURE: 'UPDATE_CANDIDAT_FAILURE',
  UPDATE_CANDIDAT_SUCCESS: 'UPDATE_CANDIDAT_SUCCESS',
};
export const candidatConstants = {
  GETBYIDUSER_CANDIDAT_REQUEST: 'GETBYIDUSER_CANDIDAT_REQUEST',
  GETBYIDUSER_CANDIDAT_FAILURE: 'GETBYIDUSER_CANDIDAT_FAILURE',
  GETBYIDUSER_CANDIDAT_SUCCESS: 'GETBYIDUSER_CANDIDAT_SUCCESS',
};


export const SallegetByIdCentreConstants = {
  GETByIdCentre_SALLE_REQUEST: 'GETByIdCentre_SALLE_REQUEST',
  GETByIdCentre_SALLE_FAILURE: 'GETByIdCentre_SALLE_FAILURE',
  GETByIdCentre_SALLE_SUCCESS: 'GETByIdCentre_SALLE_SUCCESS',
};


export const DeleteSalleConstants = {
  DELETE_SALLE_REQUEST: 'DELETE_SALLE_REQUEST',
  DELETE_SALLE_FAILURE: 'DELETE_SALLE_FAILURE',
  DELETE_SALLE_SUCCESS: 'DELETE_SALLE_SUCCESS',
};

export const AddSalleConstants = {
  ADD_SALLE_REQUEST: 'ADD_SALLE_REQUEST',
  ADD_SALLE_FAILURE: 'ADD_SALLE_FAILURE',
  ADD_SALLE_SUCCESS: 'ADD_SALLE_SUCCESS',
};
export const UpdateSalleConstants = {
  UPDATE_SALLE_REQUEST: 'UPDATE_SALLE_REQUEST',
  UPDATE_SALLE_FAILURE: 'UPDATE_SALLE_FAILURE',
  UPDATE_SALLE_SUCCESS: 'UPDATE_SALLE_SUCCESS',
};
export const ContratgetByIdFormationConstants ={
  GETByIdFORMATION_CONTRAT_REQUEST: 'GETByIdFORMATION_CONTRAT_REQUEST',
  GETByIdFORMATION_CONTRAT_FAILURE: 'GETByIdFORMATION_CONTRAT_FAILURE',
  GETByIdFORMATION_CONTRAT_SUCCESS: 'GETByIdFORMATION_CONTRAT_SUCCESS',
}

export const ContratConstants = {
  DELETE_CONTRAT_SUCCESS :'DELETE_CONTRAT_SUCCESS',
  DELETE_CONTRAT_REQUEST : 'DELETE_CONTRAT_REQUEST',
  DELETE_CONTRAT_FAILURE : 'DELETE_CONTRAT_FAILURE'
};

export const ContratFormateurConstants = {
  GET_CONTRAT_FORMATEURS_SUCCESS :'GET_CONTRAT_FORMATEURS_SUCCESS',
  GET_CONTRAT_FORMATEURS_REQUEST : 'GET_CONTRAT_FORMATEURS_REQUEST',
  GET_CONTRAT_FORMATEURS_FAILURE : 'GET_CONTRAT_FORMATEURS_FAILURE'
};

export const CategoriesConstants = {
  GET_CATEGORIES_REQUEST: 'GET_CATEGORIES_REQUEST',
  GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE',
  GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
  GET_BY_NOM_CATEGORIES_REQUEST : 'GET_BY_NOM_CATEGORIES_REQUEST',
  GET_BY_NOM_CATEGORIES_FAILURE: 'GET_BY_NOM_CATEGORIES_FAILURE',
  GET_BY_NOM_CATEGORIES_SUCCESS : 'GET_BY_NOM_CATEGORIES_SUCCESS',

  ADD_CATEGORIES_REQUEST: 'ADD_CATEGORIES_REQUEST',
  ADD_CATEGORIES_FAILURE: 'ADD_CATEGORIES_FAILURE',
  ADD_CATEGORIES_SUCCESS: 'ADD_CATEGORIES_SUCCESS',
  DELETE_CATEGORIES_SUCCESS :'DELETE_CATEGORIES_SUCCESS',
  DELETE_CATEGORIES_REQUEST : 'DELETE_CATEGORIES_REQUEST',
  DELETE_CATEGORIES_FAILURE : 'DELETE_CATEGORIES_FAILURE',
  UPDATE_CATEGORIES_SUCCESS :'UPDATE_CATEGORIES_SUCCESS',
  UPDATE_CATEGORIES_REQUEST : 'UPDATE_CATEGORIES_REQUEST',
  UPDATE_CATEGORIES_FAILURE : 'UPDATE_CATEGORIES_FAILURE'
};